In [5]:
import mlrose
import numpy as np

In [37]:
# Initialize fitness function object using pre-defined class
fitness = mlrose.OneMax()

# Define optimization problem object
problem = mlrose.DiscreteOpt(length = 8, fitness_fn = fitness, maximize=False, max_val=8)

schedule = mlrose.ExpDecay()

In [40]:
np.random.seed(1)
               
init_state = np.array([0, 1, 2, 3, 4, 5, 6, 7])
best_state, best_fitness, curve = mlrose.simulated_annealing(problem, schedule = schedule, max_attempts = 100, 
                                                      max_iters = 200, init_state = init_state, curve=True)

print(best_state)

print(best_fitness)
print(curve)

[0 0 0 0 0 0 0 0]
0.0
[-26. -22. -16. -16. -16. -16. -16. -16. -19. -18. -18. -12. -12. -12.
 -11. -13. -14. -15. -15. -15. -15. -13. -12. -12. -12. -14. -16. -16.
 -14. -14. -12. -10. -10. -10. -10.  -7.  -7.  -7.  -7.  -7.  -7.  -7.
  -7.  -7.  -7.  -7.  -7.  -7.  -7.  -7.  -7.  -5.  -5.  -5.  -5.  -5.
  -5.  -4.  -4.  -4.  -4.  -5.  -5.  -6.  -6.  -6.  -5.  -5.  -5.  -5.
  -5.  -5.  -3.  -3.  -3.  -3.  -3.  -3.  -2.  -2.  -2.  -2.  -2.  -2.
  -2.  -2.  -2.  -2.  -1.  -1.  -1.  -1.  -1.  -1.  -1.  -1.  -1.  -1.
  -1.  -1.  -1.  -1.  -1.  -1.  -1.  -1.  -1.  -1.  -1.  -1.  -1.  -1.
  -1.  -1.  -1.  -1.  -2.  -2.  -2.  -2.  -2.  -2.  -2.  -2.  -2.  -2.
  -2.  -2.  -2.  -2.  -2.  -2.  -2.  -2.  -1.  -1.  -1.  -1.  -1.  -1.
  -1.  -1.  -1.  -1.  -1.  -1.  -1.  -1.  -1.  -2.  -2.  -2.  -2.  -2.
  -2.  -2.  -2.  -2.  -2.  -2.  -2.  -2.  -2.  -2.  -2.  -2.  -2.  -1.
  -0.  -0.  -0.  -0.  -0.  -0.  -0.  -0.  -0.  -0.  -0.  -0.  -0.  -0.
  -0.  -0.  -0.  -0.  -0.  -0.  -0.  -0.  -0.  -0.  -0.

In [34]:
np.random.seed(1)

best_state, best_fitness, curve = mlrose.simulated_annealing(problem, schedule = schedule, max_attempts = 100, 
                                                      max_iters = 1000, init_state = init_state, curve=True)
print(best_state)
print(best_fitness)
curve.shape

[7 0 7 4 1 5 3 1]
0.0


(1000,)

In [41]:
np.arange(0, 100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [ ]:
problems = [mlrose.FourPeaks(), mlrose.]